#!/bin/bash

# tweak for your own needs


set -e; set -o pipefail; set -x

# http://support.illumina.com/downloads/bcl2fastq_conversion_software.html

BASE=bcl2fastq2-v2.17.1.14

# like the docs say on page 5 of bcl2fastq2-v215-User-Guide-15051736-C.pdf

TMP=./tmp
# make sure we start fresh
rm -rf ${TMP}
mkdir ${TMP}
cd ${TMP}
export TMP=`pwd`
export SOURCE=${TMP}/bcl2fastq
export BUILD=${TMP}/${BASE}-build

# depending on where you want it installed
#export INSTALL_DIR=/usr/local/${BASE}
export INSTALL_DIR=${TMP}/install/usr/local/${BASE}

wget ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/Software/bcl2fastq/${BASE}.tar.zip
unzip ${BASE}.tar.zip
tar -xvzf ${BASE}.tar.gz
mkdir ${BUILD}
cd ${BUILD}
${SOURCE}/src/configure --prefix=${INSTALL_DIR}
make
make install


